version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes: 
      - ./src-files:/var/www/html
  nginx:
    image: nginx:latest
    ports: 
      - 8085:80
    volumes: 
      - ./src-files:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root